In [1]:
import numpy as np

In [ ]:
# Create a random 3x4 matrix with value between 0-100. And perform below tasks
# i. Sort this matrix. np.sort()
# ii. Sort this matrix based on values in 2nd column.
# iii. Sort this matrix based on max value in each row.
# iv. Sort based on elements value.

In [15]:
arr = np.random.randint(1,100,size=(3,4))

print(arr)

print("====================")


sorted = np.sort(arr)

#sort by second columns

sorted_column = arr[arr[:,1].argsort()]

print(sorted_column)
print("====================")

print(sorted)


[[20 39  5 57]
 [ 3 39 53 78]
 [51 54  7 60]]
[[20 39  5 57]
 [ 3 39 53 78]
 [51 54  7 60]]
[[ 5 20 39 57]
 [ 3 39 53 78]
 [ 7 51 54 60]]
