In [2]:
import numpy as np


In [5]:
# Create a null vector of size 10 but the fifth value which is 1.

x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [15]:
# Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b)
# and print the array and avg of the array.


a = int(input("Enter a: "))
b = int(input("Enter b: "))

try:   
    arr = np.random.random(12).reshape(a,b)
except Exception as e:
    print(e)



Enter a:  4
Enter b:  4


cannot reshape array of size 12 into shape (4,4)


In [23]:
# Q-3Write a function to create a 2d array with 1 on the border and 0 inside. 
# Take 2-D array shape as (a,b) as parameter to function.



def create_arr(a,b):
    arr = np.zeros((a,b),dtype=int)
    arr[0,:] = 1
    arr[-1,:] = 1
    arr[:,0] = 1
    arr[:,-1] = 1
    
    return arr

create_arr(4,4)
    

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

In [25]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded

n = np.arange(1,10)
n

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# Q-5 Can you create a identity mattrix of shape (3,4). If yes write code for it
#we can't directly create 3x4 as identity matrix should be n*n

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [41]:
# Create a 5x5 matrix with row values ranging from 0 to 4.
arr = np.arange(5).reshape(1,5).repeat(5,axis=0)
arr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [50]:
 # Consider a random integer (in range 1 to 100) vector with shape (10,2) 
# representing coordinates, and coordinates of a point as array is given.
# Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type


arr = np.random.randint(1,101,size=(10,2))
ref_point = np.array([2,3]) 
distances = np.sqrt(np.sum((arr - ref_point) ** 2, axis=1))

distances = distances.astype(int)

print("Points: ",arr)
print("Distances: ",distances)



Points:  [[74 12]
 [20 47]
 [57 73]
 [52 93]
 [25 75]
 [51 26]
 [37 14]
 [74 27]
 [97 47]
 [82 87]]
Distances:  [ 72  47  89 102  75  54  36  75 104 116]


In [52]:
# Q-8: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

arr =np.unravel_index(100,(6,7,8))
arr

(1, 5, 4)

In [61]:
# Input Format:

# A single line of input containing space separated numbers.

# Output Format:

# Print the reverse NumPy array with type float.

# Example 1:

# Input:

# 1 2 3 4 -8 -10
# Output:

# [-10.  -8.   4.   3.   2.   1.]

user_input = input("Enter input: ")

arr = np.array(user_input.split(), dtype=float)
new_arr = arr[::-1]
new_arr

Enter input:  1 2 3 4 5


array([5., 4., 3., 2., 1.])

In [64]:
# Q-10: Elements count
# Count the number of elements of a numpy array.

# Example 1:

# Input:

# np.array([])
# Output:

# elements_count :  0
# Example 2:

# Input:

# np.array([1, 2])
# Output:

# elements_count :  2


num_arr = np.random.random(3)
print("elements count", num_arr.size)

elements count 3
