In [17]:
# Find the nearest element in the array to a given integer
import numpy as np
arr = np.array([10, 17, 24, 31, 38, 45, 52, 59])
given_element = 30

diff = np.abs(arr - given_element)

print(diff)
 
idx = np.argmin(diff)

print(idx)

nearest = arr[idx]

print(nearest)

[20 13  6  1  8 15 22 29]
3
31


In [27]:
# Replace multiples of 3 or 5 as 0 in the given array.
a = np.array([1,2,3,4,5,6,7,9])
np.where((a % 3 == 0) | (a % 5 == 0), 0, a)


array([1, 2, 0, 4, 0, 0, 7, 0])

In [20]:
a

array([1, 2, 3, 4, 5, 6, 7, 9])

In [ ]:
# Q-3: Use Fancy Indexing.
# Double the array elements at given indexes
# arr = np.arrange(10)
# indexes = [0,3,4,9]
# Result -> [ 0 1 2 6 8 5 6 7 8 18]

# Using a given array make a different array as in below example
# array = [1,2,3]
# result array -> [1 1 1 2 2 2 3 3 3]
# Internal-repetion should be as length of the array.
# Hint:

# if a is an array
# a = [2,4]
# a[[1,1,0,1]] will result in-> [4 4 2 4]


