In [2]:
import numpy as np

In [3]:
# Create a random 3x4 matrix with value between 0-100. And perform below tasks
# i. Sort this matrix. np.sort()
# ii. Sort this matrix based on values in 2nd column.
# iii. Sort this matrix based on max value in each row.
# iv. Sort based on elements value.

In [10]:
arr = np.random.randint(1,100,size=(3,4))

print(arr)

print("=========Sorted=======")


sorted = np.sort(arr)

print(sorted)

print("======Sorted By Second Col=======")


#sort by second columns

sorted_column = arr[arr[:,1].argsort()]

print(sorted_column)
print("========Sort this matrix by max val in each row ============")
sorted_row = arr[np.max(arr,axis=1).argsort()]
print(sorted_row)


sorted_elementsval = np.sort(arr, axis=None).reshape(arr.shape)
print(sorted_elementsval)



[[99 72 43 75]
 [69  7 30 68]
 [25 19 50 36]]
=========Sorted=======
[[43 72 75 99]
 [ 7 30 68 69]
 [19 25 36 50]]
======Sorted By Second Col=======
[[69  7 30 68]
 [25 19 50 36]
 [99 72 43 75]]
========Sort this matrix by max val in each row ============
[[25 19 50 36]
 [69  7 30 68]
 [99 72 43 75]]
[[ 7 19 25 30]
 [36 43 50 68]
 [69 72 75 99]]


In [ ]:
# There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.

In [ ]:
# i. Add marks every student of an extra subject in the same array.
# ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
# iii. Add extra column with sum of all subjects(5-subjects) marks
# iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.