In [ ]:
#Numpy Tricks


In [1]:
#np.sort -> return a sorted copy of an array
import numpy as np
a = np.random.randint(1,100,15)
a

array([81, 22, 50, 28, 72, 63, 23, 27,  3, 82, 13, 95, 76, 33, 68])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[22, 63, 43, 52],
       [96, 35, 36, 85],
       [25,  7, 95, 69],
       [58, 91, 40, 95],
       [37, 42, 73, 39],
       [99, 78, 61,  7]])

In [3]:
np.sort(a)

array([ 3, 13, 22, 23, 27, 28, 33, 50, 63, 68, 72, 76, 81, 82, 95])

In [4]:
np.sort(b) #row wise


array([[22, 43, 52, 63],
       [35, 36, 85, 96],
       [ 7, 25, 69, 95],
       [40, 58, 91, 95],
       [37, 39, 42, 73],
       [ 7, 61, 78, 99]])

In [5]:
np.sort(b,axis=0) #column wise

array([[22,  7, 36,  7],
       [25, 35, 40, 39],
       [37, 42, 43, 52],
       [58, 63, 61, 69],
       [96, 78, 73, 85],
       [99, 91, 95, 95]])

In [7]:
np.sort(a)[::-1] #row wise but desceding


array([95, 82, 81, 76, 72, 68, 63, 50, 33, 28, 27, 23, 22, 13,  3])

In [9]:
#np.append
# The numpy.append() appends values along the mentioned axis at the end of the array

np.append(a,200)

array([ 81,  22,  50,  28,  72,  63,  23,  27,   3,  82,  13,  95,  76,
        33,  68, 200])

In [10]:
b

array([[22, 63, 43, 52],
       [96, 35, 36, 85],
       [25,  7, 95, 69],
       [58, 91, 40, 95],
       [37, 42, 73, 39],
       [99, 78, 61,  7]])

In [12]:
np.append(b,np.zeros((b.shape[0],1)),axis=1)

array([[22., 63., 43., 52.,  0.],
       [96., 35., 36., 85.,  0.],
       [25.,  7., 95., 69.,  0.],
       [58., 91., 40., 95.,  0.],
       [37., 42., 73., 39.,  0.],
       [99., 78., 61.,  7.,  0.]])

In [16]:
np.append(
    b,
    np.random.randint(1,10,size=(b.shape[0],1)),
    axis=1
)

array([[22, 63, 43, 52,  5],
       [96, 35, 36, 85,  2],
       [25,  7, 95, 69,  9],
       [58, 91, 40, 95,  1],
       [37, 42, 73, 39,  3],
       [99, 78, 61,  7,  4]])

In [ ]:
#np.concatenate
# numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [17]:
a

array([81, 22, 50, 28, 72, 63, 23, 27,  3, 82, 13, 95, 76, 33, 68])

In [37]:
c = np.arange(8).reshape(2,4)

In [38]:
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [36]:
print(b)
print(c)

[[22 63 43 52]
 [96 35 36 85]
 [25  7 95 69]
 [58 91 40 95]
 [37 42 73 39]
 [99 78 61  7]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [41]:
np.concatenate((b,c),axis=0)

array([[22, 63, 43, 52],
       [96, 35, 36, 85],
       [25,  7, 95, 69],
       [58, 91, 40, 95],
       [37, 42, 73, 39],
       [99, 78, 61,  7],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [42]:
#np.uniqe()
# With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [44]:
#np.expand_dims()
np.expand_dims(e,axis=1)

array([[1],
       [1],
       [2],
       [2],
       [3],
       [3],
       [4],
       [4],
       [5],
       [5],
       [6],
       [6]])

In [ ]:
# np.where
# The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.


In [45]:
a

array([81, 22, 50, 28, 72, 63, 23, 27,  3, 82, 13, 95, 76, 33, 68])

In [56]:
np.where(a>50)

1

In [49]:
new_arr

[array([ True, False, False, False,  True,  True, False, False, False,
         True, False,  True,  True, False,  True])]

In [58]:
(a[a>50])

array([81, 72, 63, 82, 95, 76, 68])

In [59]:
#replace all values > 50 with zero
#np.where(condtion,true,false)

np.where(a>50,0,a)

array([ 0, 22, 50, 28,  0,  0, 23, 27,  3,  0, 13,  0,  0, 33,  0])

In [99]:
# np.argmax
# The numpy.argmax() function returns indices of the max element of the array in a particular axis.

a

array([110, 530,  50,  28,  72,  63,  23,  27,   3,  82,  13,  95,  76,
        33,  68])

In [100]:
np.argmax(a)


1

In [64]:
b

array([[22, 63, 43, 52],
       [96, 35, 36, 85],
       [25,  7, 95, 69],
       [58, 91, 40, 95],
       [37, 42, 73, 39],
       [99, 78, 61,  7]])

In [65]:
np.argmax(b,axis=1)

array([1, 0, 2, 3, 2, 0])

In [ ]:
#np.argmin -> opposite to above one.


In [ ]:
# np.cumsum
# numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [66]:
a

array([81, 22, 50, 28, 72, 63, 23, 27,  3, 82, 13, 95, 76, 33, 68])

In [71]:
np.cumsum(a)

array([ 81, 103, 153, 181, 253, 316, 339, 366, 369, 451, 464, 559, 635,
       668, 736])

In [73]:
np.cumsum(b,axis=0)

array([[ 22,  63,  43,  52],
       [118,  98,  79, 137],
       [143, 105, 174, 206],
       [201, 196, 214, 301],
       [238, 238, 287, 340],
       [337, 316, 348, 347]])

In [ ]:
# np.cumprod() -> same but products


In [ ]:
# np.percentile
# numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

In [74]:
a

array([81, 22, 50, 28, 72, 63, 23, 27,  3, 82, 13, 95, 76, 33, 68])

In [76]:
np.percentile(a,75)

74.0

In [79]:
#np.histogram

np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])


(array([1, 1, 4, 1, 0, 1, 2, 2, 2, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [ ]:
# np.corrcoef
# Return Pearson product-moment correlation coefficients.

In [81]:
salary = np.array([20000,40000,50000,60000,70000])
experience = np.array([1,2,3,4,6])

np.corrcoef(salary,experience)

array([[1.        , 0.95945946],
       [0.95945946, 1.        ]])

In [83]:
# np.isin
# With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.


items = [10,20,30,28]

In [84]:
np.isin(a,items)

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False])

In [85]:
#np.flip -> The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.
np.flip(a)


array([68, 33, 76, 95, 13, 82,  3, 27, 23, 63, 72, 28, 50, 22, 81])

In [86]:
np.flip(b)

array([[ 7, 61, 78, 99],
       [39, 73, 42, 37],
       [95, 40, 91, 58],
       [69, 95,  7, 25],
       [85, 36, 35, 96],
       [52, 43, 63, 22]])

In [87]:
b

array([[22, 63, 43, 52],
       [96, 35, 36, 85],
       [25,  7, 95, 69],
       [58, 91, 40, 95],
       [37, 42, 73, 39],
       [99, 78, 61,  7]])

In [88]:
b

array([[22, 63, 43, 52],
       [96, 35, 36, 85],
       [25,  7, 95, 69],
       [58, 91, 40, 95],
       [37, 42, 73, 39],
       [99, 78, 61,  7]])

In [ ]:
# np.put
# The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array./

In [89]:
a

array([81, 22, 50, 28, 72, 63, 23, 27,  3, 82, 13, 95, 76, 33, 68])

In [90]:
np.put(a,[0,1],[110,530])

In [91]:
a

array([110, 530,  50,  28,  72,  63,  23,  27,   3,  82,  13,  95,  76,
        33,  68])

In [92]:
#np.delete -> returns a new array of deleted items
a

array([110, 530,  50,  28,  72,  63,  23,  27,   3,  82,  13,  95,  76,
        33,  68])

In [93]:
np.delete(a,0)

array([530,  50,  28,  72,  63,  23,  27,   3,  82,  13,  95,  76,  33,
        68])

In [ ]:
### Set functions

# - np.union1d -> joins 2 array with uniqe itme
# - np.intersect1d -> gives back elements same in both
# - np.setdiff1d -> a mai hai b mai nahi hai
# - np.setxor1d -> dono ke comman hai baki hata dega
# - np.in1d




In [94]:
#np.clip() -> is used to clip (limit) the values in array

a

array([110, 530,  50,  28,  72,  63,  23,  27,   3,  82,  13,  95,  76,
        33,  68])

In [95]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 50, 28, 72, 63, 25, 27, 25, 75, 25, 75, 75, 33, 68])