In [ ]:
#Numpy

In [2]:
#What is numpy?
# NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides
# a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment
# of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting,
# I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

# At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types



In [ ]:
#creating numpy arrays

In [5]:
#np.array
#1d array

import numpy as np
a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [6]:
#2d array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
#3d array | tensor

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
#dtype

np.array([1,2,3],dtype=bool)
np.array([1,2,3],dtype=float)
# np.array([1,2,3],dtype=complex)


array([1., 2., 3.])

In [14]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [20]:
#with reshape
x = np.arange(1,13).reshape(2,6)
y = np.arange(1,13).reshape(3,4)

print(x)
print("--------------")
print(y)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
--------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
#np.ones and np.zeros

np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.random.random((3,4))

array([[0.81977666, 0.27611592, 0.90433601, 0.71763819],
       [0.21561966, 0.54299897, 0.18437134, 0.28951662],
       [0.61876768, 0.02616349, 0.65223447, 0.13681226]])

In [28]:
#np.linspace
#gives numbers from a given range to a another range in equal distances
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [29]:
np.identity(3)
#diagon items are one rest are zero

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
#np attributes
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [38]:
#ndim -> gives info about dimensions of arr
a2.ndim

2

In [39]:
#shape -> how many items in dimension

a2.shape

#it has (3,4) means 3 rows 4 columns

(3, 4)

In [40]:
#size -> it gives how many total items are there in a numpy arr

print(a2.size)

12


In [41]:
#itemsize
a1.itemsize


8

In [42]:
#dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int64
float64
int64


In [43]:
#astype -> changing datatypes 
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [44]:
#Array Operations
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [46]:
#scalar operations

#arthmetic

print(a1 * 2)
print(a1 / 2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


In [51]:
#relational
a2 > 15
a2 == 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [52]:
#vector operations
a1 + a2


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [53]:
#Array functions

a1 = np.random.random((3,3))
a1 = np.round(a1 * 100)
a1


array([[44., 42., 96.],
       [62., 18., 21.],
       [54., 40., 47.]])

In [59]:
#max/min/sum/prod

np.max(a1)
np.min(a1)
np.prod(a1)



422093144309760.0

In [64]:
# 0 -> col
# 1 -> row

#min in a row

np.max(a1,axis=1)

#min in a column

np.max(a1,axis=0)


#sum in a row
np.sum(a1,axis=1)

#sum in a column
np.sum(a1,axis=0)

array([160., 100., 164.])

In [65]:
# mean/median
np.mean(a1,axis=1)

array([60.66666667, 33.66666667, 47.        ])

In [66]:
#log and exponents
np.exp(a1)

array([[1.28516001e+19, 1.73927494e+18, 4.92345829e+41],
       [8.43835667e+26, 6.56599691e+07, 1.31881573e+09],
       [2.83075330e+23, 2.35385267e+17, 2.58131289e+20]])

In [75]:
#Indexing and Slicing

x1 = np.arange(10)
x2 = np.arange(12).reshape(3,4)
x3 = np.arange(8).reshape(2,2,2)


x2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
#indexing
x1[-1]
x1[1]


1

In [81]:
x2[1,2]

# x2[row,column]

6

In [82]:
x2[2,2]

10

In [83]:
x3
#let's get 7 from it

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [84]:
x3[1,1,1]

7

In [85]:
x3[0,1,0]


2

In [ ]:
#Slicing
#extract multiple items at once


In [86]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
#in 1d
a1[2:5]

array([2, 3, 4])

In [92]:
x2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
#in 2d
x2[0,:]

array([0, 1, 2, 3])

In [93]:
x2[:,2]

array([ 2,  6, 10])

In [96]:
x2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [98]:
x2[::,::3]

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11]])

In [113]:
x2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [114]:
x2[1,::3]

array([4, 7])

In [ ]:
#slicing in 3d

In [116]:
x3 = np.arange(27).reshape(3,3,3)

In [117]:
x3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [120]:
x3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [121]:
x3[0,1]

array([3, 4, 5])

In [128]:
x3[1,:,1]

array([10, 13, 16])

In [133]:
x3[2,1::1,1::]

array([[22, 23],
       [25, 26]])

In [134]:
x3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [136]:
x3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
#Iteration on numpy array

In [138]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [144]:
for i in np.nditer(x3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [143]:
x3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [149]:
#transpose
# converts rows to columns and vise vera

y = np.transpose(x3)
print(y)

# or
a2.T

[[[ 0  9 18]
  [ 3 12 21]
  [ 6 15 24]]

 [[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]]


array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [148]:
x3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [152]:
#ravel - converts 2d or 3d arr into 1d

x3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [157]:
#stacking

#horizantal stacking

h1 = np.arange(12).reshape(3,4)
h2 = np.arange(12,24).reshape(3,4)

print(h1)
print(h2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [163]:
np.hstack((h1,h2))


array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [164]:
np.vstack((h1,h2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#stacking requirment : shape of arrays should be same


In [165]:
#splitting

h1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [167]:
np.hsplit(h1,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [184]:
j1 = np.arange(16).reshape(4,5)

ValueError: cannot reshape array of size 16 into shape (4,5)

In [172]:
np.vstack(j1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])